
server:
  port: 8083
  servlet:
    context-path: /payment

spring:
  application:
    name: payment
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&serverTimezone=UTC
    username: root
    password: joaoflavio

  rabbitmq:
    addresses: amqps://picxtlgp:70EnkLONoqVU_6EXM2XOdzaXBcISPAk5@chimpanzee.rmq.cloudamqp.com/picxtlgp

crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.product.queue