server:
  port: 8082
  servlet:
    context-path: /crud

spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: amqps://picxtlgp:70EnkLONoqVU_6EXM2XOdzaXBcISPAk5@chimpanzee.rmq.cloudamqp.com/picxtlgp

  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/crud?useSSL=false&serverTimezone=UTC
    username: root
    password: joaoflavio

crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.product.routingkey


security:
  jwt:
    token:
      secret-key: key_microservices

